### ISSUE TITLE
Extensive documentation is missing

### ISSUE THREAD

**Issue by Setnea** [dizak/mothulity#11]
Would be really nice if readme could:
- briefly introduce mothulity basic execution options,
- provide example of usage i.e. based on MiSeqSOP dataset mentioned in "example data section".

**Comment by dizak** [comment]
Also, the output should be described. This is way too much for the README in my opinion and should be moved to the wiki. So, in fact, there are a few things to do:

- Upload images of the example output.
- Create the wiki with a description of each options section from CLI and advanced ways of using mothulity, eg custom templates.
- Make README brief and concise again.

**Comment by dizak** [comment]
Closing as #53 solved these.
