### ISSUE TITLE
OTU-clustering without mothur

### ISSUE THREAD

**Issue by dizak** [dizak/mothulity#14]
As the OTU-clustering part is the most computing power and time-consuming part of the analysis, there is an urgent need for using some alternative way of computing it.

**Comment by dizak** [comment]
[Vsearch](https://github.com/torognes/vsearch) is an open-source alternative to [usearch](https://www.drive5.com/usearch/) and is already **implemented** in mothur! Hopefully, is it more efficient than clustering with currently used method.

**Comment by dizak** [comment]
[Vsearch](https://github.com/torognes/vsearch), at least used with the agc method, is seemingly more efficient than opticlust (yeah, thank you, captain). Benchmarking is needed to discern whether this is the solution.

**Comment by dizak** [comment]
@Setnea Are we keeping this issue as [vsearch](https://github.com/torognes/vsearch) implementation really does its job?

**Comment by Setnea** [comment]
I think vsearch fulfilled previously unmet needs, so the issue can be closed.
