### ISSUE TITLE
Drop Python2 and Python3.5

### ISSUE THREAD

**Issue by dizak** [dizak/mothulity#169]
Python 2 is dead. Also, we are getting errors for Python 3.5 and below. It is time to drop them.

This issue should be top-priority, as it blocks everything else.

**Comment by Setnea** [comment]
I agree. Even though I have mixed feelings about python2 sunset (so many bioinformatics tools relay on it...), it was really about time. Looking for solutions that will be old-version-support-friendly sometimes pushed us to do really silly workarounds.

**Comment by Setnea** [comment]
Edited files:
- .travis
- setup.py

I am really confused, I was so sure we mentioned the 2.x support in many more places, but I can't find any.

**Comment by Setnea** [comment]
Edited files:
- mothulity
- mothulity_dbaser
- mothulity_fc 
- mothulity_draw

Fixing imports in order to remove print_function and six library (for py2 and py3 cross-support).

**Comment by Setnea** [comment]
Solved
