### ISSUE TITLE
Wraper for main mothulity script

### ISSUE THREAD

**Issue by Setnea** [dizak/mothulity#60]
# Proposed change

Create bash wraper for main mothulity python script, remove shebang edition from installation.

**Comment by dizak** [comment]
I am somewhat reluctant as this is a working solution that passes the CI tests. I have never encountered any problems with it.

Though we are using the conda envs, there's [a piece from the virtualenv documentation](https://virtualenv.pypa.io/en/stable/userguide/#activate-script) that says directly that it is ok to use such a shebang.
