### ISSUE TITLE
No final html file

### ISSUE THREAD

**Issue by t-walter** [dizak/mothulity#93]
# v. 1.6.1

# Description
Seems to work properly but no Krona and final fancy html files appeared (partial result files and other figures are generated). The issue occurs on MiSeqSOP test dataset as well as on other analyzed data. It appears that this problem does not occur when mothulity is installed in its own environment.

# Steps to reproduce
1. install mothulity from pip with no separate environment
`pip install mothulity`
2. run it on Silva v119 or v132 (location of databases specified each time with --align/taxonomy-database argument, not set with --set-align/taxonomy-database-path if it could matter) in slurm, in my case for Silva v119:
`mothulity /fastq/files/location/ --job-name test --run sbatch --resources phi --align-database /location/of/silva.nr_v119.align --taxonomy-database /location/silva.nr_v119.tax`
3. inspect result files, I have identified following errors in logfiles:
[ERROR]: did not complete parsimony
[ERROR]: group M00967_43_..., ..., ... is not in your count table. Please correct.
[ERROR]: M00967_43_..., ..., ... is not in your count table. Please correct.

# Expected behaviour
Generation of all expected result files.

# Actual behaviour
No Krona and final html files.

**Comment by dizak** [comment]
Thanks!

Which version of ```mothur``` do you use in this case (when ```mothulity``` is not installed in its own environment)?

**Comment by t-walter** [comment]
Mothur version=1.38.1

It is the same version as on another machine, on which I have installed `mothulity` in its own environment and it works properly.

**Comment by dizak** [comment]
OK, I was able to reproduce your error. It is probably caused by lacking KronaTools. It was not embedded with the package.
